apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-backend
  namespace: sample-guestbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: backend
        image: timblackops/guestbook:main
        ports:
        - containerPort: 3000
        env:
        - name: BG_COLOR
          value: "#f0f8ff"  # Light blue
          # value: "#ff0000"  # Red
        - name: REDIS_URL
          value: "redis://redis-guestbook-backend:6379"    